rapidxml::xml_node
xml_node(node_type type)
Constructs an empty node with the specified type. Consider using memory_pool of appropriate document to allocate nodes manually. type Type of node to construct.
node_type type() const
Gets type of node. Type of node.
Referenced by xml_node::append_node, memory_pool::clone_node, xml_node::document, xml_node::insert_node, xml_node::prepend_node.
xml_document<Ch>* document() const
Gets document of which node is a child. Pointer to document that contains this node, or 0 if there is no parent document.
References rapidxml::node_document, xml_base::parent, xml_node::type.
xml_node<Ch>* first_node(const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
Gets first child node, optionally matching node name. name Name of child to find, or 0 to return first child regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero name_size Size of name, in characters, or 0 to have size calculated automatically from string case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters Pointer to found child, or 0 if not found.
References xml_base::name, xml_base::name_size.
Referenced by xml_node::append_node, memory_pool::clone_node, xml_node::prepend_node, xml_node::remove_all_nodes, xml_node::remove_first_node, xml_node::remove_last_node, xml_node::remove_node.
xml_node<Ch>* last_node(const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
Gets last child node, optionally matching node name. Behaviour is undefined if node has no children. Use first_node() to test if node has children. name Name of child to find, or 0 to return last child regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero name_size Size of name, in characters, or 0 to have size calculated automatically from string case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters Pointer to found child, or 0 if not found.
References xml_base::name, xml_base::name_size.
xml_node<Ch>* previous_sibling(const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
Gets previous sibling node, optionally matching node name. Behaviour is undefined if node has no parent. Use parent() to test if node has a parent. name Name of sibling to find, or 0 to return previous sibling regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero name_size Size of name, in characters, or 0 to have size calculated automatically from string case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters Pointer to found sibling, or 0 if not found.
References xml_base::name, xml_base::name_size.
xml_node<Ch>* next_sibling(const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
Gets next sibling node, optionally matching node name. Behaviour is undefined if node has no parent. Use parent() to test if node has a parent. name Name of sibling to find, or 0 to return next sibling regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero name_size Size of name, in characters, or 0 to have size calculated automatically from string case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters Pointer to found sibling, or 0 if not found.
References xml_base::name, xml_base::name_size.
xml_attribute<Ch>* first_attribute(const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
Gets first attribute of node, optionally matching attribute name. name Name of attribute to find, or 0 to return first attribute regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero name_size Size of name, in characters, or 0 to have size calculated automatically from string case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters Pointer to found attribute, or 0 if not found.
References xml_base::name, xml_base::name_size.
Referenced by xml_node::append_attribute, memory_pool::clone_node, xml_node::prepend_attribute, xml_node::remove_all_attributes, xml_node::remove_attribute, xml_node::remove_first_attribute, xml_node::remove_last_attribute.
xml_attribute<Ch>* last_attribute(const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
Gets last attribute of node, optionally matching attribute name. name Name of attribute to find, or 0 to return last attribute regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero name_size Size of name, in characters, or 0 to have size calculated automatically from string case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters Pointer to found attribute, or 0 if not found.
References xml_base::name, xml_base::name_size.
void type(node_type type)
Sets type of node. type Type of node to set.
void prepend_node(xml_node< Ch > *child)
Prepends a new child node. The prepended child becomes the first child, and all existing children are moved one position back. child Node to prepend.
References xml_node::first_node, xml_node::m_next_sibling, xml_base::m_parent, xml_node::m_prev_sibling, rapidxml::node_document, xml_base::parent, xml_node::type.
Referenced by xml_node::insert_node.
void append_node(xml_node< Ch > *child)
Appends a new child node. The appended child becomes the last child. child Node to append.
References xml_node::first_node, xml_node::m_next_sibling, xml_base::m_parent, xml_node::m_prev_sibling, rapidxml::node_document, xml_base::parent, xml_node::type.
Referenced by xml_node::insert_node, xml_document::parse.
void insert_node(xml_node< Ch > *where, xml_node< Ch > *child)
Inserts a new child node at specified place inside the node. All children after and including the specified node are moved one position back. where Place where to insert the child, or 0 to insert at the back. child Node to insert.
References xml_node::append_node, xml_node::m_prev_sibling, rapidxml::node_document, xml_base::parent, xml_node::prepend_node, xml_node::type.
void remove_first_node()
Removes first child node. If node has no children, behaviour is undefined. Use first_node() to test if node has children.
References xml_node::first_node, xml_node::m_next_sibling, xml_base::m_parent.
Referenced by xml_node::remove_node.
void remove_last_node()
Removes last child of the node. If node has no children, behaviour is undefined. Use first_node() to test if node has children.
References xml_node::first_node, xml_base::m_parent, xml_node::m_prev_sibling.
Referenced by xml_node::remove_node.
void remove_node(xml_node< Ch > *where)
Removes specified child from the node.
References xml_node::first_node, xml_node::m_next_sibling, xml_base::m_parent, xml_node::m_prev_sibling, xml_base::parent, xml_node::remove_first_node, xml_node::remove_last_node.
void remove_all_nodes()
Removes all child nodes (but not attributes).
References xml_node::first_node.
Referenced by xml_document::clear, xml_document::parse.
void prepend_attribute(xml_attribute< Ch > *attribute)
Prepends a new attribute to the node. attribute Attribute to prepend.
References xml_node::first_attribute, xml_attribute::m_next_attribute, xml_base::m_parent, xml_attribute::m_prev_attribute, xml_base::parent.
Referenced by xml_node::insert_attribute.
void append_attribute(xml_attribute< Ch > *attribute)
Appends a new attribute to the node. attribute Attribute to append.
References xml_node::first_attribute, xml_attribute::m_next_attribute, xml_base::m_parent, xml_attribute::m_prev_attribute, xml_base::parent.
Referenced by xml_node::insert_attribute.
void insert_attribute(xml_attribute< Ch > *where, xml_attribute< Ch > *attribute)
Inserts a new attribute at specified place inside the node. All attributes after and including the specified attribute are moved one position back. where Place where to insert the attribute, or 0 to insert at the back. attribute Attribute to insert.
References xml_node::append_attribute, xml_attribute::m_prev_attribute, xml_base::parent, xml_node::prepend_attribute.
void remove_first_attribute()
Removes first attribute of the node. If node has no attributes, behaviour is undefined. Use first_attribute() to test if node has attributes.
References xml_node::first_attribute, xml_attribute::m_next_attribute, xml_base::m_parent.
Referenced by xml_node::remove_attribute.
void remove_last_attribute()
Removes last attribute of the node. If node has no attributes, behaviour is undefined. Use first_attribute() to test if node has attributes.
References xml_node::first_attribute, xml_base::m_parent, xml_attribute::m_prev_attribute.
Referenced by xml_node::remove_attribute.
void remove_attribute(xml_attribute< Ch > *where)
Removes specified attribute from node. where Pointer to attribute to be removed.
References xml_node::first_attribute, xml_attribute::m_next_attribute, xml_base::m_parent, xml_attribute::m_prev_attribute, xml_base::parent, xml_node::remove_first_attribute, xml_node::remove_last_attribute.
void remove_all_attributes()
Removes all attributes of node.
References xml_node::first_attribute.
Referenced by xml_document::clear, xml_document::parse.
xml_node(const xml_node &)
void operator=(const xml_node &)
node_type m_type
xml_node<Ch>* m_first_node
xml_node<Ch>* m_last_node
xml_attribute<Ch>* m_first_attribute
xml_attribute<Ch>* m_last_attribute
xml_node<Ch>* m_prev_sibling
Referenced by xml_node::append_node, xml_node::insert_node, xml_node::prepend_node, xml_node::remove_last_node, xml_node::remove_node.
xml_node<Ch>* m_next_sibling
Referenced by xml_node::append_node, xml_node::prepend_node, xml_node::remove_first_node, xml_node::remove_node.