rapidxml::memory_pool
memory_pool()
Constructs empty pool with default allocator functions.
~memory_pool()
Destroys pool and frees all the memory. This causes memory occupied by nodes allocated by the pool to be freed. Nodes allocated from the pool are no longer valid.
References memory_pool::clear.
xml_node<Ch>* allocate_node(node_type type, const Ch *name=0, const Ch *value=0, std::size_t name_size=0, std::size_t value_size=0)
Allocates a new node from the pool, and optionally assigns name and value to it. If the allocation request cannot be accomodated, this function will throw std::bad_alloc. If exceptions are disabled by defining RAPIDXML_NO_EXCEPTIONS, this function will call parse_error_handler() function. type Type of node to create. name Name to assign to the node, or 0 to assign no name. value Value to assign to the node, or 0 to assign no value. name_size Size of name to assign, or 0 to automatically calculate size from name string. value_size Size of value to assign, or 0 to automatically calculate size from value string. Pointer to allocated node. This pointer will never be NULL.
References xml_base::name, xml_base::value.
Referenced by memory_pool::clone_node.
xml_attribute<Ch>* allocate_attribute(const Ch *name=0, const Ch *value=0, std::size_t name_size=0, std::size_t value_size=0)
Allocates a new attribute from the pool, and optionally assigns name and value to it. If the allocation request cannot be accomodated, this function will throw std::bad_alloc. If exceptions are disabled by defining RAPIDXML_NO_EXCEPTIONS, this function will call parse_error_handler() function. name Name to assign to the attribute, or 0 to assign no name. value Value to assign to the attribute, or 0 to assign no value. name_size Size of name to assign, or 0 to automatically calculate size from name string. value_size Size of value to assign, or 0 to automatically calculate size from value string. Pointer to allocated attribute. This pointer will never be NULL.
References xml_base::name, xml_base::value.
Referenced by memory_pool::clone_node.
Ch* allocate_string(const Ch *source=0, std::size_t size=0)
Allocates a char array of given size from the pool, and optionally copies a given string to it. If the allocation request cannot be accomodated, this function will throw std::bad_alloc. If exceptions are disabled by defining RAPIDXML_NO_EXCEPTIONS, this function will call parse_error_handler() function. source String to initialize the allocated memory with, or 0 to not initialize it. size Number of characters to allocate, or zero to calculate it automatically from source string length; if size is 0, source string must be specified and null terminated. Pointer to allocated char array. This pointer will never be NULL.
xml_node<Ch>* clone_node(const xml_node< Ch > *source, xml_node< Ch > *result=0)
Clones an xml_node and its hierarchy of child nodes and attributes. Nodes and attributes are allocated from this memory pool. Names and values are not cloned, they are shared between the clone and the source. Result node can be optionally specified as a second parameter, in which case its contents will be replaced with cloned source node. This is useful when you want to clone entire document. source Node to clone. result Node to put results in, or 0 to automatically allocate result node Pointer to cloned node. This pointer will never be NULL.
References memory_pool::allocate_attribute, memory_pool::allocate_node, xml_node::first_attribute, xml_node::first_node, xml_base::name, xml_base::name_size, xml_node::type, xml_base::value, xml_base::value_size.
void clear()
Clears the pool. This causes memory occupied by nodes allocated by the pool to be freed. Any nodes or strings allocated from the pool will no longer be valid.
Referenced by memory_pool::~memory_pool.
void set_allocator(alloc_func *af, free_func *ff)
Sets or resets the user-defined memory allocation functions for the pool. This can only be called when no memory is allocated from the pool yet, otherwise results are undefined. Allocation function must not return invalid pointer on failure. It should either throw, stop the program, or use longjmp() function to pass control to other place of program. If it returns invalid pointer, results are undefined. User defined allocation functions must have the following forms: void *allocate(std::size_t size); void free(void *pointer); af Allocation function, or 0 to restore default function ff Free function, or 0 to restore default function
void* allocate_memory(std::size_t size)
block* m_block
std::size_t m_size
block m_static_block
alloc_func* m_alloc_func
free_func* m_free_func