rapidxml::xml_base
xml_base()
Ch* name() const
Gets name of the node. Interpretation of name depends on type of node. Note that name will not be zero-terminated if parse_no_string_terminators option was selected during parse. Use name_size() function to determine length of the name. Name of node, or empty string if node has no name.
Referenced by memory_pool::allocate_attribute, memory_pool::allocate_node, memory_pool::clone_node, xml_node::first_attribute, xml_node::first_node, xml_node::last_attribute, xml_node::last_node, xml_base::name, xml_attribute::next_attribute, xml_node::next_sibling, xml_attribute::previous_attribute, xml_node::previous_sibling.
std::size_t name_size() const
Gets size of node name, not including terminator character. This function works correctly irrespective of whether name is or is not zero terminated. Size of node name, in characters.
Referenced by memory_pool::clone_node, xml_node::first_attribute, xml_node::first_node, xml_node::last_attribute, xml_node::last_node, xml_attribute::next_attribute, xml_node::next_sibling, xml_attribute::previous_attribute, xml_node::previous_sibling.
Ch* value() const
Gets value of node. Interpretation of value depends on type of node. Note that value will not be zero-terminated if parse_no_string_terminators option was selected during parse. Use value_size() function to determine length of the value. Value of node, or empty string if node has no value.
Referenced by memory_pool::allocate_attribute, memory_pool::allocate_node, memory_pool::clone_node, xml_base::value.
std::size_t value_size() const
Gets size of node value, not including terminator character. This function works correctly irrespective of whether value is or is not zero terminated. Size of node value, in characters.
Referenced by memory_pool::clone_node.
void name(const Ch *name, std::size_t size)
Sets name of node to a non zero-terminated string. See Ownership Of Strings . Note that node does not own its name or value, it only stores a pointer to it. It will not delete or otherwise free the pointer on destruction. It is reponsibility of the user to properly manage lifetime of the string. The easiest way to achieve it is to use memory_pool of the document to allocate the string - on destruction of the document the string will be automatically freed. Size of name must be specified separately, because name does not have to be zero terminated. Use name(const Ch *) function to have the length automatically calculated (string must be zero terminated). name Name of node to set. Does not have to be zero terminated. size Size of name, in characters. This does not include zero terminator, if one is present.
void name(const Ch *name)
Sets name of node to a zero-terminated string. See also Ownership Of Strings and xml_node::name(const Ch *, std::size_t). name Name of node to set. Must be zero terminated.
References xml_base::name.
void value(const Ch *value, std::size_t size)
Sets value of node to a non zero-terminated string. See Ownership Of Strings . Note that node does not own its name or value, it only stores a pointer to it. It will not delete or otherwise free the pointer on destruction. It is reponsibility of the user to properly manage lifetime of the string. The easiest way to achieve it is to use memory_pool of the document to allocate the string - on destruction of the document the string will be automatically freed. Size of value must be specified separately, because it does not have to be zero terminated. Use value(const Ch *) function to have the length automatically calculated (string must be zero terminated). value value of node to set. Does not have to be zero terminated. size Size of value, in characters. This does not include zero terminator, if one is present.
void value(const Ch *value)
Sets value of node to a zero-terminated string. See also Ownership Of Strings and xml_node::value(const Ch *, std::size_t). value Vame of node to set. Must be zero terminated.
References xml_base::value.
xml_node<Ch>* parent() const
Gets node parent. Pointer to parent node, or 0 if there is no parent.
Referenced by xml_node::append_attribute, xml_node::append_node, xml_node::document, xml_node::insert_attribute, xml_node::insert_node, xml_node::prepend_attribute, xml_node::prepend_node, xml_node::remove_attribute, xml_node::remove_node.
Ch* m_name
Ch* m_value
std::size_t m_name_size
std::size_t m_value_size
xml_node<Ch>* m_parent
Referenced by xml_node::append_attribute, xml_node::append_node, xml_node::prepend_attribute, xml_node::prepend_node, xml_node::remove_attribute, xml_node::remove_first_attribute, xml_node::remove_first_node, xml_node::remove_last_attribute, xml_node::remove_last_node, xml_node::remove_node.
static Ch* nullstr()